title = "Squires' Garden Party"
baseURL = "https://squiresgardenpart.firebaseapp.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Squires' Garden Party"
    author = "James Hargreaves"
    description = ""
    logoBig = "/images/banner.png"
    logoLong = "/images/bannerLong.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true